spring.application.name=api-gateway
server.port=8080

# JWT
jwt.secret=dG9wLXNlY3JldC1rZXktZm9yLWR1bXAtYXBwLWRldi1vbmx5LWNoYW5nZS1pbi1wcm9k

# gRPC Clients
grpc.client.auth-service.address=static://localhost:9091
grpc.client.auth-service.negotiation-type=plaintext
grpc.client.event-service.address=static://localhost:9094
grpc.client.event-service.negotiation-type=plaintext
grpc.client.media-service.address=static://localhost:9093
grpc.client.media-service.negotiation-type=plaintext

# CORS
cors.allowed-origins=${CORS_ORIGINS:*}
